### ISSUE TITLE
ブラウザバックアラートがviewファイルに反映されない問題

### ISSUE THREAD

**Issue by otakazuto** [otakazuto/quiz_by_syuare#9]
### アセットコンパイルを使用する場合の手順

　app/javascript/ファイル名.js  にJavascriptファイルの作成
　↓
　app/javascript/packs/application.js のファイルに
　import './ファイル名（拡張子なし）'
　↓
　viewファイルに
　`<%= javascript_pack_tag 'application' %>`
　or
　`<%= javascript_include_tag '作成したjsファイル名' %>`

※issues作成中に気付いたところ
 javascript_include_tagは、指定したJavaScriptファイルを読み込むための<script>タグを生成し、それをウェブページのヘッダーまたはフッターに挿入します。これにより、ウェブアプリケーションで必要なJavaScriptコードを適切に組み込むことができる。

### アセットコンパイルを使用しない場合の手順

1　viewファイルに<script>タグを使用し、そこに直接コードを書きこむ
2　app/javascript/ファイル名.js  にJavascriptファイルの作成
　 ↓
　 app/javascript/packs/application.js のファイルに
　 import './ファイル名'
　↓
　viewファイルに
　`<script src="/assets/ファイル名.js"></script>`

issues作成中

### 実際に試したこと

※issue作成中に見つけたブラウザバックとpopstateイベントの関係について、分かりやすく書かれていた記事
[https://qiita.com/kdi0618/items/72ac070cf37066b3617c](url)

1つ目　最初に試していたコード
　// app/assets/javascripts/custom.js

```
document.addEventListener("DOMContentLoaded", function () {
  window.onpopstate = function (e) {
    // 戻るボタンが押された際に実行する処理を記述
    if (confirm("戻るボタンを押してもよろしいですか？")) {
      // ユーザーがOKを選択した場合の処理
    } else {
      // ユーザーがキャンセルを選択した場合の処理
      e.preventDefault(); // ブラウザのデフォルトの戻る動作を無効にする
      history.pushState(null, null, location.href); // ブラウザの履歴を元に戻す
    }
  };
});
```

　//app/view/layouts/application.html.erb

`<%= javascript_include_tag "custom" %>`

上記のコードを追加したが、viewファイルに反映ず、エラー文も出ていない。

2つ目
　// app/assets/javascripts/custom.js

```
window.addEventListener('popstate', function (e) {
  if (confirm('前のページに戻りますか？')) {
    // ユーザーがOKを選択した場合の処理
  } else {
    // ユーザーがキャンセルを選択した場合の処理
    history.pushState(null, null, location.href); // ブラウザの履歴を元に戻す
  }
});
```

　//app/view/layouts/application.html.erb

`<%= javascript_include_tag "custom" %>`

このコードもviewファイルとエラー文がなかった。

3つ目
　// app/assets/javascripts/custom.js

`window.onbeforeunload = function() {
  return "このページを離れようとしています。続行しますか？";
};`

　//app/view/layouts/application.html.erb

`<%= javascript_include_tag "custom" %>`

このコードは、ページを移動する際にアラートを出すコードです。
このコードを追加したが、アラートが出るが、アラート文が違った。1つ目2つ目と違い、アラートが表示されており、上記のコードにreturnメソッドを使用しているので、アラートが出た可能性があり、コードが発火したと考えられるが、アラート文が違う原因は不明である。また、ブラウザの戻るボタンを押した際にはアラート文が出されなかったので。ブラウザバック時は発火しないと考えられる。

4つ目
　// app/assets/javascripts/custom.js

```
window.onpopstate = function(event) {
  if (event.state) {
    alert("戻るボタンがクリックされました！");
  }
};
```

　//app/view/layouts/application.html.erb

`<%= javascript_pack_tag 'application' %>`

このコードは、1つ目2つ目と同じ、viewへの反映及びエラー文がない結果となった。

**次に上記のコードをアセットパイプラインに追加しない方法で試したが、結果は同じだった。**

5つ目
　下記のコードは、特定のリンクをクリックした際にアラートを出すことができるか試した際のコードです。

`<a href="/" id="myLink">ページに移動</a>`

```
<script>
  const link = document.getElementById("myLink");
  link.addEventListener("click", function(event) {
    event.preventDefault(); // デフォルトのリンク動作をキャンセル
    alert("ページに移動します！");
    // ここでページ遷移の処理を行う
    window.location.href = "/"; // 例: 新しいページにリダイレクト
  });
</script>
```

結果は、リンクをクリックした際にアラートと、アラート文が正しく表示された。

### 現在の状況
・コードをほぼ理解していない状況で開発しているため、エラー文が表示されていないので、どこに問題があるのかいまいち理解できていない。

### 今後の課題
・ブラウザバックとpopstateイベントの関係についての記事から、history.pushStateが関係しているかもしれないので、詳しく調べてみてもいいかも。
・アセットコンパイルに追加する方法ではうまくいっていないので、アセットコンパイルについて見直すか、アセットコンパイルに追加しない方法で考えたほうがいいかもしれない。

**Comment by otakazuto** [comment]
問題が解決しました。

**Comment by 327yuto** [comment]
この問題については、サービスの仕様を改めて考える必要がありそうです。
下記記事より
**「セキュリティ観点の問題であり、Chrome はデフォルトの「戻る」ボタン動作のハイジャックを意図的に防止しているからです」**

qiita記事：https://qiita.com/ryoutancobu/items/eb908659e109c19ab1e1
